name: Craftgate Go Client CI

on:
  release:
    types: [ published ]

jobs:
  build-artifact:
    name: Publish Library
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go 1.18
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
          cache: true
          cache-dependency-path: go.sum

      - name: Build and Publish
        run: echo hello
